AllCops:
  TargetRubyVersion: 3.1

  Exclude:
    - 'init/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'config/boot.rb'
    - 'config/puma.rb'
    - 'db/schema.rb'
    #修正案や改善案を提案
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true

# 機能ごとにgemをまとめているため、アルファベット順にしない
Bundler/OrderedGems:
  Enabled: false

# メソッドをグループ分けして書き順を揃えておくと読みやすくなる。
Layout/ClassStructure:
  Enabled: true

#コメントのインデントが正しいかどうかを確認し、コメントのインデントの修正を自動的に行わないようにする
Layout/CommentIndentation:
  AutoCorrect: false

# 自動修正を実施した際、不適切な修正があったため、autocorrectableの対象にしない
Layout/MultilineArrayBraceLayout:
  AutoCorrect: false

Metrics/BlockLength:
  Exclude:
  - 'config/environments/development.rb'
  - 'config/environments/production.rb'
  - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/Documentation:
  Enabled: false
